// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1cxNzfod2fy1lAjN3NQ_1-HTCK6XwaXs',
    appId: '1:203270850968:web:b427407580fae4cef783ed',
    messagingSenderId: '203270850968',
    projectId: 'teamhive-ab0aa',
    authDomain: 'teamhive-ab0aa.firebaseapp.com',
    storageBucket: 'teamhive-ab0aa.firebasestorage.app',
    measurementId: 'G-5NV5LP1N0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiCOb0ICrUZkDJqEupIBs-zVwhVeyXZtk',
    appId: '1:203270850968:android:0fda8918f74bceb4f783ed',
    messagingSenderId: '203270850968',
    projectId: 'teamhive-ab0aa',
    storageBucket: 'teamhive-ab0aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkbgMp19yiloaZguoIbcyf-J6xqktOZg',
    appId: '1:203270850968:ios:956f6715c57b0b5ef783ed',
    messagingSenderId: '203270850968',
    projectId: 'teamhive-ab0aa',
    storageBucket: 'teamhive-ab0aa.firebasestorage.app',
    iosBundleId: 'com.example.teamHive',
  );
}
